### ISSUE TITLE
Captured image not showing only in Samsung galaxy s4

### ISSUE THREAD

**Issue by deepakdezire23** [nguyenhoanglam/ImagePicker#54] opened 2017-01-31 19:34 UTC
After going through so many blog and hints i didnt found solution. I want to show captured image in android image view. Below you can find the code i am using to capture an image from camera.
Please provide the solution that will work for all the devices.

   private void onLaunchCamera() {

        // create Intent to take a picture and return control to the calling application
        Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        filepath1 = FileProvider.getUriForFile(MainActivity.this, BuildConfig.APPLICATION_ID + ".provider", getPhotoFileUri(photofileName));
        intent.putExtra(android.content.Intent.EXTRA_STREAM, filepath1); // set the image file name
        // If you call startActivityForResult() using an intent that no app can handle, your app will crash.
        // So as long as the result is not null, it's safe to use the intent.
        if (intent.resolveActivity(getPackageManager()) != null) {
            // Start the image capture intent to take photo
            startActivityForResult(intent, CAPTURE_IMAGE_ACTIVITY_REQUEST_CODE);
        }

    }

    private File getPhotoFileUri(String photofileName) {

        // Only continue if the SD Card is mounted
        if (isExternalStorageAvailable()) {
            // Get safe storage directory for photos
            // Use `getExternalFilesDir` on Context to access package-specific directories.
            // This way, we don't need to request external read/write runtime permissions.
            File mediaStorageDir = new File(
                    getExternalFilesDir(Environment.DIRECTORY_PICTURES), APP_Name);
            // Create the storage directory if it does not exist
            if (!mediaStorageDir.exists() && !mediaStorageDir.mkdirs()) {
                Log.d(APP_Name, "failed to create directory");
            }
           imagefilepath = "content:"+mediaStorageDir.getPath()+photofileName;
            return (new File(mediaStorageDir.getPath() + File.separator + photofileName));
            // Return the file target for the photo based on filename

        }
        return null;

    }

    /**
     * It will check if SD card is mounted to the view or not.
     *
     * @return
     */
    private boolean isExternalStorageAvailable() {
        String state = Environment.getExternalStorageState();
        return state.equals(Environment.MEDIA_MOUNTED);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        Uri photoUri = null;
        Bitmap bm;

        if (resultCode == RESULT_OK) {
            if (data != null) {

                photoUri=data.getData();
                Log.d("selectedimage", ""+photoUri);
                String[] filePath = { MediaStore.Images.Media.DATA };
                Cursor c = getContentResolver().query(photoUri,filePath, null, null, null);
                c.moveToFirst();
                int columnIndex = c.getColumnIndex(filePath[0]);
                String picturePath = c.getString(columnIndex);
                c.close();
                Bitmap thumbnail = (BitmapFactory.decodeFile(picturePath));
            
                  m_Imagebutton.setImageBitmap(thumbnail);
            }
        }
    }
Thanks in advance.

**Comment by Rainer-Lang** [comment] 2017-09-07 09:49
@deepakdezire23 Have you tried an image lib like Glide to show the image?

**Comment by nguyenhoanglam** [comment] 2017-09-07 09:55
@deepakdezire23 Please update to version 1.2.0 and let me know if the issue is gone!

**Comment by wwwwebexpert** [comment] 2017-09-07 16:13
Yes I have tired it using Glide but no success. Then i have found solution for this issue with minor updation.

**Comment by Rainer-Lang** [comment] 2017-09-07 16:19
@wwwwebexpert Could you explain?

**Comment by nguyenhoanglam** [comment] 2017-09-08 01:11
@deepakdezire23 Have you tried ver 1.2.0?

**Comment by nguyenhoanglam** [comment] 2020-05-09 16:34
Hi guys,
Version 1.4.0 is now available. Please check it out and close this issue if the error's gone away!
Thank you so much!

**Closed** 2020-06-03 11:54 UTC
