### ISSUE TITLE
Images captured using camera is not automatically selected

### ISSUE THREAD

**Issue by saneeshvs** [nguyenhoanglam/ImagePicker#62] opened 2017-06-12 09:18 UTC
When I capture a image using the camera provided in the ImagePicker it doesn't get selected automatically, rather we have to select it from the folder, is there a option to select images captured using camera automatically.

**Comment by Rainer-Lang** [comment] 2017-09-07 14:51
@nguyenhoanglam Duplicate of https://github.com/nguyenhoanglam/ImagePicker/issues/52 ? -> Close this?

**Comment by nguyenhoanglam** [comment] 2020-05-09 16:35
Hi guys,
Version 1.4.0 is now available. Please check it out and close this issue if the error's gone away!
Thank you so much!

**Closed** 2020-05-09 16:40 UTC
